name: tcc_apoio_psicologico
description: "Plataforma inteligente de apoio psicológico complementar - TCC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de Estado e Rotas
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0

  # Responsividade e UI
  responsive_framework: ^1.1.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1

  # Firebase
  firebase_core: ^2.27.0          # core inicialização
  firebase_auth: ^4.17.8          # autenticação
  cloud_firestore: ^4.15.8        # banco de dados
  firebase_messaging: ^14.7.19    # push notifications (opcional)
  google_sign_in: ^6.2.1



  # Configurações de ambiente
  flutter_dotenv: ^5.0.2
  # Gráficos
  fl_chart: ^0.66.0

  # Notificações locais e Fuso Horário
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

  # Comunicação e outros
  http: ^1.2.0
  web_socket_channel: ^2.4.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
